version: "3.9"

services:
  base:
    image: marcpartensky/arch
    build:
      context: base
    ports:
      - "10022:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  xorg:
    image: marcpartensky/arch:xorg
    build:
      context: xorg
    environment:
      DISPLAY: :1
        # ipc: host
        # privileged: true
    user: $USER
      # pid: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.X1-lock:/tmp/.X1-lock
      # - /tmp:/tmp
      # devices:
      # - /dev/dri
      - /var/cache/pacman/pkg:/var/cache/pacman/pkg
      - arch_home:/home/marc

  vnc:
    image: marcpartensky/arch:vnc
    build:
      context: vnc
    ports:
      - "18080:8080"
      - "15900:5900"
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - /var/cache/pacman/pkg:/var/cache/pacman/pkg
      - arch_home:/home/marc

  parabola:
    image: marcpartensky/arch:parabola
    build:
      context: parabola

volumes:
  arch_home:

