version: "3.9"

services:
  arch:
    image: marcpartensky/arch
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "10022:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  arch_vnc:
    image: marcpartensky/arch:vnc
    build:
      context: vnc
      dockerfile: ./Dockerfile
    ports:
      - "10022:22"
      - "15901:5901"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
