version: "3.9"

services:
  base:
    image: marcpartensky/arch
    build:
      context: base
    ports:
      - "10022:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  xorg:
    image: marcpartensky/arch:xorg
    build:
      context: xorg
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri

  vnc:
    image: marcpartensky/arch:vnc
    build:
      context: vnc
    ports:
      - "18080:8080"
      - "15900:5900"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  parabola:
    image: marcpartensky/arch:parabola
    build:
      context: parabola
