version: "3.9"

services:
  arch:
    image: marcpartensky/arch
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  arch_vnc:
    image: marcpartensky/arch:vnc
    build:
      context: vnc
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
